#!/usr/bin/env ruby
=begin 
Homepage:	http://sqwee.rubyforge.org/
Author:		Justin Collins (http://presidentbeef.com/)
Copyright:	2007, Justin Collins
License:	GPL

    This file is part of Sqwee.

    Sqwee is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Sqwee is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Sqwee.  If not, see <http://www.gnu.org/licenses/>.
=end


$stderr.puts "Setting server root directory..."

File.open("config/.lighttpd.conf.bak", "w") do |f|
	File.readlines("./config/lighttpd.conf").each do |line|
		case line
		when /^server.document-root\s+=\s+"#{Dir.pwd}"/
			f.puts line
		when /^server.document-root\s+=\s+".*"/
			f.puts "server.document-root        = \"#{Dir.pwd}\""
		when /^cgi.assign = \(".rhtml" => ".*"\)/
			f.puts "cgi.assign = (\".rhtml\" => \"#{Dir.pwd}\/bin\/eruby\")"
		else
			f.puts line
		end
	end
end

`mv ./config/.lighttpd.conf.bak ./config/lighttpd.conf`

if File.exist? "lighttpd.pid"
	pid = File.read "lighttpd.pid"
	if pid != ""
		$stderr.puts "Attempting to shut down Lighttpd..."
		`kill #{pid}`
	end
end

$stderr.puts "Attempting to start Lighttpd..."

`export LD_LIBRARY_PATH=./extlib/lighttpd_modules/: ; ./bin/lighttpd -m ./extlib/lighttpd_modules/ -f config/lighttpd.conf`
